import localFont from "next/font/local";
import "./globals.css";
import { Inter, Plus_Jakarta_Sans } from "next/font/google";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { getLoggedInUser } from "@/actions/auth";

const inter = Plus_Jakarta_Sans({
  subsets: ["latin"],
  display: "swap",
  weight: "500",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const user = await getLoggedInUser();
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <Navbar user={user} />
        <section className="min-h-[90vh]">{children}</section>i
        <Footer />
      </body>
    </html>
  );
}
